name: pvihk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pulp=2.8.0
  - pyside6=6.7.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - coin-or-cbc          # ersetzt "cbc" durch den stabilen Paketnamen
  - pip
  - pip:
      - fpdf==1.7.2
      - pyinstaller
