name: pvihk
channels:
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.17.4
  - amply=0.1.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.8
  - coincbc=2.10.10
  - cyrus-sasl=2.1.27
  - docutils=0.21.2
  - expat=2.7.0
  - freetype=2.12.1
  - gettext=0.21.1
  - icu=73.2
  - importlib-metadata=8.6.1
  - jpeg=9e
  - krb5=1.20.1
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.43
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxml2=2.13.7
  - libxslt=1.1.41
  - libzlib=1.2.13
  - llvm-openmp=20.1.3
  - lz4-c=1.9.4
  - macholib=1.16.3
  - minizip=4.0.3
  - mysql=8.4.0
  - ncurses=6.4
  - openldap=2.6.4
  - openssl=3.5.0
  - packaging=25.0
  - pcre2=10.42
  - pip=25.0
  - pulp=2.8.0
  - pyinstaller=6.7.0
  - pyinstaller-hooks-contrib=2025.3
  - pyparsing=3.2.3
  - pyside6=6.7.2
  - python=3.12.2
  - python_abi=3.12
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - fpdf==1.7.2

