name: Build Windows EXE and Auto-Release with Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment-windows.yml
          activate-environment: pvihk
          auto-update-conda: true
          channels: conda-forge,defaults

      - name: Install pip-only packages
        run: |
          pip install pyinstaller fpdf==1.7.2

      - name: Find pulp path
        id: find_pulp
        shell: bash -l {0}
        run: |
          PULP_PATH=$(python -c "import pulp, os; print(os.path.dirname(pulp.__file__))")
          echo "pulp-path=$PULP_PATH" >> $GITHUB_OUTPUT

      - name: Read build number
        id: read_build
        shell: bash
        run: |
          echo "BUILD_NUMBER=$(cat build_number.txt)" >> $GITHUB_ENV

      - name: Build with PyInstaller
        shell: bash -l {0}
        run: |
          pyinstaller \
            --clean \
            --noconfirm \
            --onefile \
            --windowed \
            --log-level=DEBUG \
            --icon=PVIHK.ico \
            --hidden-import=pulp \
            --add-data "${{ steps.find_pulp.outputs.pulp-path }};pulp" \
            --add-data "build_number.txt;." \
            --add-binary "assets/cbc.exe;." \
            --collect-submodules PySide6 \
            --collect-data PySide6 \
            --distpath dist \
            pvihk.py

      - name: Debug LICENSE exist
        run: dir LICENSE.txt

      - name: Run NSIS
        run: makensis /DVERSION=v1.0.${{ env.BUILD_NUMBER }} installer/installer.nsi

      - name: Check if EXEs were built
        shell: pwsh
        run: |
          $version = "v1.0.$env:BUILD_NUMBER"
          $setupPath = "dist/PVIHK-$version`_setup.exe"
          if (!(Test-Path "dist/pvihk.exe")) {
            throw "pvihk.exe not found"
          }
          if (!(Test-Path $setupPath)) {
            throw "$setupPath not found"
          }

      - name: Create GitHub Release with versioned installer
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ env.BUILD_NUMBER }}
          name: Release v1.0.${{ env.BUILD_NUMBER }}
          body: Version 1.0.${{ env.BUILD_NUMBER }}
          files: |
            dist/pvihk.exe
            dist/PVIHK-v1.0.${{ env.BUILD_NUMBER }}_setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

