name: Build Windows EXE via Conda + PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment-windows.yml
          activate-environment: pvihk
          auto-update-conda: true
          channels: conda-forge,defaults

      - name: Install pip-only packages
        run: |
          pip install fpdf==1.7.2

      - name: Find pulp path
        id: find_pulp
        run: |
          for /f "delims=" %%i in ('python -c "import pulp, os; print(os.path.dirname(pulp.__file__))"') do set "PULP_PATH=%%i"
          echo pulp-path=%PULP_PATH% >> %GITHUB_OUTPUT%
        shell: cmd

      - name: Build with PyInstaller
        shell: bash -l {0}
        run: |
          pyinstaller \
            --noconfirm \
            --onefile \
            --windowed \
            --icon=PVIHK.ico \
            --hidden-import=pulp \
            --add-data "${{ steps.find_pulp.outputs.pulp-path }};pulp" \
            --collect-submodules PySide6 \
            --collect-data PySide6 \
            --distpath dist \
            pvihk.py


      - name: Check if EXE was built
        run: |
          if not exist dist\pvihk.exe (
            echo Build failed: EXE not found.
            exit 1
          )
        shell: cmd


      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: pvihk-exe
          path: dist/pvihk.exe


